### PR TITLE
GUAC-1275: Netherlands keyboard layout created

### PR DESCRIPTION
**Pull request by IT-Experte**

### CODE REVIEW

**Comment by mike-jumper** [comment]
Why are 62ffd49 and 2eaf56b separate commits with identical messages? They should really just be one commit, especially since 62ffd49 by itself would break the Dutch translation.

Please note: there is almost *never* a good reason for having multiple commits with identical messages. Either they accomplish one logical change (and should be one commit), or are two distinct changes (and should have different messages).

**Comment by IT-Experte** [comment]
Commit c887f3a replace the filename with the new layout name. Is it better to change the name? 

e.g.: "GUAC-1275: Netherlands keyboard layout filename replaced"

"-"        "URL_OSK_LAYOUT" : "layouts/en-us-qwerty.json"
"+"        "URL_OSK_LAYOUT" : "layouts/nl-nl-qwerty.json"

**Comment by mike-jumper** [comment]
> Commit c887f3a replace the filename with the new layout name. Is it better to change the name?

I'm not sure what you mean. Commit c887f3a appears to have nothing to do with changing the Dutch on-screen keyboard layout. Its message, which does accurately reflect the changes therein, reads: "GUAC-298: Add VNC parameter for clipboard encoding."

> e.g.: "GUAC-1275: Netherlands keyboard layout filename replaced"

That sounds fine.

**Comment by IT-Experte** [comment]
I have created a new pull request.

**Pull request closed without merging**
