### PR TITLE
GUAC-1046: Fix of doc/guacamole-example

### PR DESCRIPTION
**Pull request by karatheodory**
Hello!

The provided example was not working, so I've added some fixes. After that I was able to successfully run the example on jetty9 for 'ssh' protocol.

Best regards,
 Vasily

### CODE REVIEW

**Comment by mike-jumper** [comment]
Hi Vasily,

Thanks for the contribution!

Have you taken a look at our [contribution guidelines](https://github.com/glyptodon/guacamole-client/blob/master/CONTRIBUTING)?

I have no problem with the changes you suggest at present, but we do need a signed CLA to safely merge things, and preferably a corresponding issue in JIRA. Signing the CLA only needs to be done once per contributor. More information is in the link above.

Thanks again, and let me know if you have any questions.

**Comment by karatheodory** [comment]
Hello Mike!

Sorry for a delay and thank you for your answer!

Attached are photos of the agreement, I will send the scanned copies as
soon as possible.

Thank you for the product! Hope that this and future contributions will be
helpful.

Best regards,
Vasily

Hi Vasily,

Thanks for the contribution!

Have you taken a look at our contribution guidelines
<https://github.com/glyptodon/guacamole-client/blob/master/CONTRIBUTING>?

I have no problem with the changes you suggest at present, but we do need a
signed CLA to safely merge things, and preferably a corresponding issue in
JIRA. Signing the CLA only needs to be done once per contributor. More
information is in the link above.

Thanks again, and let me know if you have any questions.

—
Reply to this email directly or view it on GitHub
<https://github.com/glyptodon/guacamole-client/pull/72#issuecomment-72284407>
.

**Comment by karatheodory** [comment]
Hello Mike!

Please find the JIRA issue related to the example fix by the link below:

https://glyptodon.org/jira/browse/GUAC-1046

Best regards,
 Vasily

2015-02-03 0:33 GMT+06:00 Vasily Loginov <loginov.vasily@gmail.com>:

**Comment by mike-jumper** [comment]
Thanks, Vasily. A photo would be sufficient for the time being, but it looks like GitHub stripped the attachments from your email.

You can always email me directly at mike.jumper@guac-dev.org or, if you've succeeded in scanning it, simply email the scanned copy to cla-submissions@glyptodon.org.

**Comment by mike-jumper** [comment]
Thanks - signed CLA received.

**Comment by mike-jumper** [comment]
All merged. In the future, please tag your commit messages with the JIRA issue number, as shown in the [contribution guidelines](https://github.com/glyptodon/guacamole-client/blob/master/CONTRIBUTING), so the tracking system can associate each commit with its corresponding issue.

Thanks again for the contribution!

**Comment by karatheodory** [comment]
Thank you!

2015-02-05 0:51 GMT+06:00 Mike Jumper <notifications@github.com>:

**Pull request merged**
