### PR TITLE
GUAC-1472: Implement a hack for IME activation keycode quirk on Windows

### PR DESCRIPTION
**Pull request by moriyoshi**

### CODE REVIEW

**Comment by mike-jumper** [comment]
We definitely can't have such a hack within the JavaScript API. Having a new property to control the hack called `nativeIMEActivationKeycodeHackEnabled` seems equally bad...

Is there not some way to take this "quirk" into account without hackery? What is the quirk that you are trying to work around in the first place?

**Comment by moriyoshi** [comment]
The rationale was written in the corresponding JIRA issue.  Anyways I don't think this is to be closed because anyone who uses Japanese keyboard will definitely have the same problem with me and find this patch helping his/her issue.

**Comment by moriyoshi** [comment]
As for the following comment:

> We definitely can't have such a hack within the JavaScript API.

https://github.com/glyptodon/guacamole-client/blob/master/guacamole-common-js/src/main/webapp/modules/Keyboard.js#L1055-L1058

This portion pretty much looks like a hack to me, doesn't it?

As the hack is needed because of the browser quirks, this has to be handled in the JavaScript API so that the users can switch on/off the feature on their own.

**Comment by mike-jumper** [comment]
There is no question that hacks may sometimes be necessary, but I am not (yet?) convinced that is the case here. I would like to:

1. Look into this further before committing to a hack.
2. Avoid properties like `nativeIMEActivationKeycodeHackEnabled`. Working around browser quirks is one thing, but we really should not have properties like this in the public API.

> Anyways I don't think this is to be closed because anyone who uses Japanese keyboard will definitely have the same problem with me and find this patch helping his/her issue.

This particular PR is closed only because (1) we do not have yet sufficient justification for the hack and (2) we cannot have a property like `nativeIMEActivationKeycodeHackEnabled` in the API. If a user wants this patch, GitHub makes it permanently available. The PR is not deleted; it's simply not going to be merged in its current state, and we believe the underlying concept needs more research before a particular fix (hack or not) is chosen.

**Comment by moriyoshi** [comment]
> (2) we cannot have a property like nativeIMEActivationKeycodeHackEnabled in the API. 

This needs more clarification.  Why can't we while there is no way to get around it without such an option provided?  **In general** public APIs should not propose kind of workaround to its users that is avoidable technically, but it is just an ideal in front of inconsistent browser behavior.

As no settlement has been reached so far because there's too little information to conclude this,  I don't even think this particular PR should have been closed.  It appears that you were guessing the hack would never be necessary because the information I had collected and present was simply wrong.

**Comment by mike-jumper** [comment]
@moriyoshi, please calm down and try not take this personally. The problem that your proposed changes are meant to address needs more research. This PR is premature and thus is closed.

The thing to do now is continue this discussion civilly and constructively [on the issue in JIRA](https://glyptodon.org/jira/browse/GUAC-1472) so that a better solution can be found. Since the problem definitely exists (and the issue has been rephrased to cover the problem and not a specific possible solution), the JIRA issue has been re-opened.

Regarding the flag, no, we cannot have a `nativeIMEActivationKeycodeHackEnabled` flag. A flag which describes itself as a hack does not belong in the public API, and a workaround for browser behavior should not require such a flag.

Please keep in mind that the intent of `Guacamole.Keyboard` is to provide consistent keyboard event handling across browsers, absorbing any quirks internally as necessary. Having such a flag runs counter to the intent of `Guacamole.Keyboard` - it *should* be able to make such decisions itself and internally.

**Pull request closed without merging**
