### PR TITLE
GUAC-1254: Merge contributed German OSK layout

### PR DESCRIPTION
**Pull request by mike-jumper**
This change merges the contributed OSK layout from #216, at least as it was when the PR was first opened.

I have added the following additional changes after review:

1. Renamed from "qwerty" to "qwertz"
2. Updated the German layout URL translation string
3. Implemented usage AltGr (should not use "Caps" and "Shift" for this)
4. Removed the duplicated "^" key
5. German abbreviations and additional symbols for keys that require them
6. Stylistic changes to spacing

### CODE REVIEW

**Comment by IT-Experte** [comment]
I have solved #1 and #2.

**Comment by mike-jumper** [comment]
Thanks, @IT-Experte, but it doesn't matter at this point as we've already fixed those issues ourselves during the initial review that is now complete.

If there are any issues with the changes as they stand here, definitely let us know so we can fix them prior to merge.

**Comment by mike-jumper** [comment]
For reference, this is the final result of all this:

screenshot 2015-07-16 at 3 32 37 pm

**Comment by IT-Experte** [comment]
Thank you. There was problem with the key positioning, but you have got it solved. It looks great.

**Pull request merged**
